CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Announcements" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Title" text,
    "Message" text,
    "ExpireDate" timestamp with time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Announcements" PRIMARY KEY ("Id")
);

CREATE TABLE "Assets" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FileName" text,
    "FilePath" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Assets" PRIMARY KEY ("Id")
);

CREATE TABLE "Stories" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Title" text,
    "Text" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Stories" PRIMARY KEY ("Id")
);

CREATE TABLE "UserRoles" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "MarkedWords" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Word" text,
    "Definition" text,
    "StoryId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_MarkedWords" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MarkedWords_Stories_StoryId" FOREIGN KEY ("StoryId") REFERENCES "Stories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Users" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Username" text,
    "Email" text,
    "Phone" text,
    "PasswordHash" text,
    "RegisteredAt" timestamp with time zone NOT NULL,
    "ProfilePictureId" bigint,
    "UserRoleId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Assets_ProfilePictureId" FOREIGN KEY ("ProfilePictureId") REFERENCES "Assets" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_Users_UserRoles_UserRoleId" FOREIGN KEY ("UserRoleId") REFERENCES "UserRoles" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Contents" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "Title" text,
    "Description" text,
    "FileKey" text,
    "FileUrl" text,
    "FileSize" bigint NOT NULL,
    "Type" integer NOT NULL,
    "Status" integer NOT NULL,
    "DurationLimit" integer NOT NULL,
    "Duration" integer NOT NULL,
    "IsTopContent" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Contents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Contents_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserActivities" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "UploadDate" timestamp with time zone NOT NULL,
    "IsContentDeleted" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_UserActivities" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserActivities_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserCards" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "MarkedWordId" bigint NOT NULL,
    "IsLearned" boolean NOT NULL,
    "LearnedAt" timestamp with time zone,
    "ReviewCount" integer NOT NULL,
    "LastReviewedAt" timestamp with time zone,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_UserCards" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserCards_MarkedWords_MarkedWordId" FOREIGN KEY ("MarkedWordId") REFERENCES "MarkedWords" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserCards_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Comments" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ContentId" bigint NOT NULL,
    "Text" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Comments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Comments_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Comments_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Likes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ContentId" bigint NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Likes_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Likes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE "WeeklyRankings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "ContentId" bigint NOT NULL,
    "LikeCount" integer NOT NULL,
    "Rank" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone,
    "DeletedAt" timestamp with time zone,
    "IsDeleted" boolean NOT NULL,
    "CreatedById" bigint,
    "UpdatedById" bigint,
    "DeletedById" bigint,
    CONSTRAINT "PK_WeeklyRankings" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WeeklyRankings_Contents_ContentId" FOREIGN KEY ("ContentId") REFERENCES "Contents" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_WeeklyRankings_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

INSERT INTO "UserRoles" ("Id", "CreatedAt", "CreatedById", "DeletedAt", "DeletedById", "IsDeleted", "Name", "UpdatedAt", "UpdatedById")
VALUES (1, TIMESTAMPTZ '2025-07-02T15:24:42.171967Z', NULL, NULL, NULL, FALSE, 'admin', NULL, NULL);
INSERT INTO "UserRoles" ("Id", "CreatedAt", "CreatedById", "DeletedAt", "DeletedById", "IsDeleted", "Name", "UpdatedAt", "UpdatedById")
VALUES (2, TIMESTAMPTZ '2025-07-02T15:24:42.171967Z', NULL, NULL, NULL, FALSE, 'user', NULL, NULL);

CREATE INDEX "IX_Comments_ContentId" ON "Comments" ("ContentId");

CREATE INDEX "IX_Comments_UserId" ON "Comments" ("UserId");

CREATE INDEX "IX_Contents_UserId" ON "Contents" ("UserId");

CREATE INDEX "IX_Likes_ContentId" ON "Likes" ("ContentId");

CREATE INDEX "IX_Likes_UserId" ON "Likes" ("UserId");

CREATE INDEX "IX_MarkedWords_StoryId" ON "MarkedWords" ("StoryId");

CREATE INDEX "IX_UserActivities_UserId" ON "UserActivities" ("UserId");

CREATE INDEX "IX_UserCards_MarkedWordId" ON "UserCards" ("MarkedWordId");

CREATE INDEX "IX_UserCards_UserId" ON "UserCards" ("UserId");

CREATE UNIQUE INDEX "IX_UserRoles_Name" ON "UserRoles" ("Name");

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_ProfilePictureId" ON "Users" ("ProfilePictureId");

CREATE UNIQUE INDEX "IX_Users_Username" ON "Users" ("Username");

CREATE INDEX "IX_Users_UserRoleId" ON "Users" ("UserRoleId");

CREATE INDEX "IX_WeeklyRankings_ContentId" ON "WeeklyRankings" ("ContentId");

CREATE INDEX "IX_WeeklyRankings_UserId" ON "WeeklyRankings" ("UserId");

SELECT setval(
    pg_get_serial_sequence('"UserRoles"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "UserRoles") + 1,
        nextval(pg_get_serial_sequence('"UserRoles"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250702152443_Initial', '8.0.6');

COMMIT;

START TRANSACTION;

UPDATE "UserRoles" SET "CreatedAt" = TIMESTAMPTZ '2025-07-30T11:18:58.920922Z'
WHERE "Id" = 1;

UPDATE "UserRoles" SET "CreatedAt" = TIMESTAMPTZ '2025-07-30T11:18:58.920922Z'
WHERE "Id" = 2;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250730111859_ChangedConnectionString', '8.0.6');

COMMIT;

START TRANSACTION;

UPDATE "UserRoles" SET "CreatedAt" = TIMESTAMPTZ '2025-07-30T17:29:11.538486Z'
WHERE "Id" = 1;

UPDATE "UserRoles" SET "CreatedAt" = TIMESTAMPTZ '2025-07-30T17:29:11.538486Z'
WHERE "Id" = 2;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250730172912_SuperAdmin', '8.0.6');

COMMIT;

